export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_PROD_CART_UNITS = "UPDATE_PROD_CART_UNITS";
export const UPDATE_PROD_CART_PRICE = "UPDATE_PROD_CART_PRICE";
export const UPDATE_PROD_CART_DISCOUNT = "UPDATE_PROD_CART_DISCOUNT";
export const UPDATE_PROD_CART_SIGN = "UPDATE_PROD_CART_SIGN";
export const SELECT_PROD_CART_ITEM = "SELECT_PROD_CART_ITEM";
export const SELECT_PAYMENT_TYPE = "SELECT_PAYMENT_TYPE";

